### ISSUE TITLE
Download doesn't complete

### ISSUE THREAD

**Issue by goncaloperes** [alexgand/springer_free_books#33]
Mine is stopping at 63% (255/407).

```
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    myfile = requests.get(new_url, allow_redirects=True)
  File "C:\Users\...\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\...\venv\lib\site-packages\requests\sessions.py", line 683, in send
    r.content
  File "C:\Users\...\venv\lib\site-packages\requests\models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
MemoryError

```

Any guidance here?

**Comment by victormm2000** [comment]
How did you reach that point??
I've just run the main.py file but it doesn't find module requests
